### ISSUE TITLE
[Slack] Be able to receive events from Slack Events API

### ISSUE THREAD

**Issue by aballiet** [kestra-io/plugin-notifications#110]
### Feature description

Currently it's not possible to subscribe to Slack Events using their API : https://api.slack.com/apis/connections/events-api#using-events-api due to a "challenge" mechanism explained [here](https://api.slack.com/apis/connections/events-api#challenge). Regular Webhook trigger does not work.

I think being able to react to Slack events / store them somewhere using Kestra is a great feature 👍 .

Solution might involve creating a custom trigger (if possible) as suggested by @anna-geller

**Comment by anna-geller** [comment]
Next steps: build an MVP with emoji reaction events

**Comment by anna-geller** [comment]
Ludo mentioned it would be complex so for now, we implement it in the form of a tutorial https://kestra.io/docs/tutorials/slack-webhook#example-automation-ai-chatbot 

if insufficient for the users, we can reopen later with the flow outputs solution suggested by @Ben8t: 

```yaml
id: slack-event
namespace: dev
tasks:
  - id: hello
    type: io.kestra.core.tasks.log.Log
    message: Kestra team wishes you a great day!

outputs:
   - id: challenge
     value: {{ trigger.body.challenge }} # this being exposed by webhook HTTP response

triggers:
  - id: webhook
    type: io.kestra.core.models.triggers.types.Webhook
    key: "test"
```
