### ISSUE TITLE
Make sure all *Execution tasks can be used in an error branch of a flow

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/plugin-notifications#117]
## Problem
To support users migrating from listeners, we should make all Execution notification tasks work with `errors`. 

Currently, this will not work as Execution tasks are waiting for event from a Flow trigger (or listener)

However, we want to find a solution to this and support that use case.

## Acceptance criteria
In the future, this flow should work:

```yaml
id: failing_task
namespace: prod
tasks:
  - id: fail
    type: io.kestra.plugin.scripts.shell.Commands
    runner: PROCESS
    commands:
      - exit 1
errors:
  - id: send_alert
    type: io.kestra.plugin.notifications.slack.SlackExecution
    url: https://reqres.in/api/slack
    channel: "#general"
    executionId: "{{execution.id}}"
```
