### ISSUE TITLE
Allow namespace files in MailSend activity

### ISSUE THREAD

**Issue by johnkm516** [kestra-io/plugin-notifications#149]
### Feature description

I have a MailSend activity with an HTML content which includes images. 
Currently, the MailSend activity does not have a `namespaceFiles` attribute. It expects an internal storage URI that I cannot provide unless I download the image into the Kestra's internal storage every time the flow is executed, creating copies of the same image. 

I am currently using the img src as a base64 inline, and while this works this causes the webserver UI to crash due to the huge string which makes the flow difficult to work with.

As a side note it would be great if there was some more detailed documentation on using an html content with the embedded image option.

**Comment by anna-geller** [comment]
you can use all namespace files in all plugins already as long as you read the file's content rather than accessing it via path i.e. `{{ read('your_file.png') }}` should already work. Additionally, you can wrap your `MailSend` task in a `WorkingDirectory` task which has `namespaceFiles.enabled` option allowing you to then access Namespace Files via path too 

if this info doesn't help, can you share your flow? (redact sensitive info)

**Comment by Ben8t** [comment]
Trying to get a workaround about this case. This flow almost works:

```yaml
id: email
namespace: kestra.sandbox
tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 🚀


  - id: download
    type: io.kestra.plugin.core.namespace.DownloadFiles
    namespace: kestra.sandbox
    files:
      - "test.jpg"

  - id: send_email
    type: io.kestra.plugin.notifications.mail.MailSend
    from: onboardin@resend.dev
    to: benoit@kestra.io
    username: resend
    password: "{{ secret('RESEND_API') }}"
    host: smtp.resend.com
    port: 465
    subject: "test"
    embeddedImages:
      - name: test.jpg
        uri:  '{{ outputs.download.files["/test.jpg"] }}'
        contentType: image/jpeg
    htmlTextContent: |
      "Failure alert for flow <img src='test.jpg'></img>"
```

I've uploaded test.jpg into the NamespaceFiles.
Email is sent, but the image is corrupted

![image](https://github.com/user-attachments/assets/3e06cafb-8516-4090-a28e-6f6f79c0313c)
![image](https://github.com/user-attachments/assets/eee8adcd-baf2-4fde-b6ee-c71fe2fbb4f1)
