### ISSUE TITLE
Slack webhook task fails when URL is present in the message text: `io.micronaut.http.client.exceptions.HttpClientResponseException: Bad Request`

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-notifications#157]
### Issue description

reproducer:

```yaml
id: slack
namespace: company.team

variables:
  slack_message: |
    Validate resource request.
    To approve the request, click on the Resume button here
    http://localhost:28080/ui/executions/{{flow.namespace}}/{{flow.id}}/{{execution.id}}.

tasks:
  - id: send_approval_request
    type: io.kestra.plugin.notifications.slack.SlackIncomingWebhook
    url: https://reqres.in/api/slack
    payload: |
      {
        "channel": "#devops",
        "text": "{{ render(vars.slack_message) }}"
      }
```

**Comment by anna-geller** [comment]
using `| json` works!

```yaml
id: slack
namespace: company.team

variables:
  slack_message: |
    Validate resource request.
    To approve the request, click on the Resume button here
    http://localhost:28080/ui/executions/{{flow.namespace}}/{{flow.id}}/{{execution.id}}.

tasks:
  - id: send_approval_request
    type: io.kestra.plugin.notifications.slack.SlackIncomingWebhook
    url: https://reqres.in/api/slack
    payload: |
      {
        "channel": "#devops",
        "text": {{ render(vars.slack_message) | json }}
      }
```
