### ISSUE TITLE
Email messages aren't rendered in Gmail

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/plugin-notifications#184]
### Describe the issue

When sending an email with the `io.kestra.plugin.notifications.mail.MailSend` task, the message is not rendered and this message appears:

![image](https://github.com/user-attachments/assets/90a81dde-2cd0-4502-8776-a9b17335cc7e)

```yaml
id: send_slack_message
namespace: kestra.bpimpaud

inputs:
  - id: message
    type: STRING

tasks:
  - id: send_email
    type: io.kestra.plugin.notifications.mail.MailSend
    from: onboardin@resend.dev
    to: benoit@kestra.io
    username: resend
    password: "<RESEND_API_KEY>"
    host: smtp.resend.com
    port: 465
    subject: "Kestra App Message"
```

### Environment

- Kestra Version: develop
