### ISSUE TITLE
Fix ignored properties (like payload) on the SlackExecution task 

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-notifications#191]
### Describe the issue

Try running this flow in response to a failed flow -- there are a bunch of properties which are entirely ignored incl:
- `payload`
- `channel` - the channel of the webhook `url` is taken instead
- `username` - the name of the Slack app is used instead
- `iconUrl` - the icon of the Slack app is used instead

We should either **fix** or **remove** any `SlackExecution` properties that are currently ignored.

```yaml
id: sla_miss_alert
namespace: alerting

tasks:
  - id: send_alert
    type: io.kestra.plugin.notifications.slack.SlackExecution
    url: xxxxx
    executionId: "{{trigger.executionId}}"
    iconUrl: "https://avatars.githubusercontent.com/u/59033362?s=48"
    username: "SLA Miss Alert"
    channel: "#random"
    payload: |
      {
        "text": "SLA breached for flow {{trigger.namespace}}.{{trigger.flowId}} with ID {{trigger.executionId}}"
      } 

triggers:
  - id: alert_on_failure
    type: io.kestra.plugin.core.trigger.Flow
    states:
      - FAILED
      - WARNING
      - CANCELLED
```

### Environment

- Kestra Version: develop

**Comment by mgabelle** [comment]
Able to reproduce ! 
I will try to understand why it is no working.

**Comment by mgabelle** [comment]
I am not sure if `channel` will ever be taken into account.
I don't know if some webhook url exist to publish to multiple channel. For now it seems the channel will always be the one of the URL

**Comment by mgabelle** [comment]
I can confirm that for execution none of the fields are taken into account : 

`payload` is always a Kestra template, we can add value (client may want to add a custom payload)
`channel` - the channel will always be the webhook url (to be deleted)

For both `username`  and `iconUrl` the Slack app info will be used but we can add these fields to the message and it will look like this (image at the bottom and username at the top of the attachements)  : 

![Image](https://github.com/user-attachments/assets/28f056fb-43a6-485f-a7d4-a1d1b1c665be)

**Comment by mgabelle** [comment]
Example flow linked to PR. Will add it also in the plugin slack execution examples.
https://github.com/kestra-io/plugin-notifications/pull/192#issuecomment-2612629743

**Comment by mgabelle** [comment]
Working as well with custom payload : 
```
id: slack-integration-custom-payload
namespace: mgabelle.tests.slack

listeners:
  - tasks:
      - id: slack-integration
        type: io.kestra.plugin.notifications.slack.SlackExecution
        url: "myWebhookUrl"
        payload: |
          {
            "text": "SLA success for flow {{flow.namespace}}.{{flow.id}} with Revision {{flow.revision}}"
          } 

tasks:
  - id: seq
    type: io.kestra.core.tasks.flows.Sequential
    tasks:
    - id: success
      type: io.kestra.plugin.core.debug.Return
      format: "{{ task.id }} > {{ taskrun.startDate }}"
```

**Comment by mgabelle** [comment]
Working with custom payload. 
Flow sample : https://github.com/kestra-io/plugin-notifications/pull/192#issuecomment-2612696024

**Comment by mgabelle** [comment]
Reopening the ticket as I have to revert it for the release :  #197

**Comment by anna-geller** [comment]
iconUrl and username are still ignored 😞 

```yaml
id: alerts_demo
namespace: company.team

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World!

afterExecution:
  - id: success
    runIf: "{{execution.state == 'SUCCESS'}}"
    type: io.kestra.plugin.notifications.slack.SlackExecution
    url: https://hooks.slack.com/services/xx/xx/xxx
    executionId: "{{execution.id}}"
    iconUrl: "https://avatars.githubusercontent.com/u/59033362?s=48"
    username: "Kestra Alerts"
```
