### ISSUE TITLE
The `htmlTextContent` is ignored on the MailExecution task

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-notifications#196]
### Describe the issue

![image](https://github.com/user-attachments/assets/5d40e512-efd7-43da-b934-f4b607741326)

I was using this flow:

```yaml
id: llm_explain_error
namespace: anna

tasks:
  - id: bad_python_task
    type: io.kestra.plugin.scripts.python.Script
    script: |
      myvar = 1
      print(myvar[0])

errors:
  - id: ai
    type: io.kestra.plugin.openai.ChatCompletion
    apiKey: "{{ secret('OPENAI_API_KEY') }}"
    model: gpt-4o
    clientTimeout: 100
    prompt: | 
      My Python script generated an error. 
      Provide a short explanation of what might have caused it and how to fix it. 
      Error log — {{errorLogs()}}

  - id: mail
    type: io.kestra.plugin.notifications.mail.MailExecution
    from: xxxx
    to: xxx
    username: xxx
    host: xxx
    port: 465
    password: "{{ secret('EMAIL_PASSWORD') }}"
    sessionTimeout: 6000
    subject: "Failure alert for flow {{ flow.namespace }}.{{ flow.id }}"
    htmlTextContent: "Here are more details about the error: {{ outputs.ai.choices[0].message.content }}"
    executionId: "{{ execution.id }}"
```

### Environment

- Kestra Version: develop

**Comment by mgabelle** [comment]
I am trying to reproduce, do you use a Gmail account or something else for this one ? @anna-geller

**Comment by anna-geller** [comment]
The recipient is Gmail, the sender is my private mail

**Comment by mgabelle** [comment]
I am not able to reproduce. I tried with this flow : 
```
id: mail_execution
namespace: mgabelle.tests.email

tasks:
  - id: bad_python_task
    type: io.kestra.plugin.scripts.python.Script
    script: |
      myvar = 1
      print(myvar[0])

errors:
  - id: mail
    type: io.kestra.plugin.notifications.mail.MailExecution
    from: mgabelle@kestra.io
    to: "xx private email address xx"
    username: mgabelle@kestra.io
    host: smtp.gmail.com
    port: 465
    password: "** my kestra gmail password **"
    sessionTimeout: 6000
    subject: "Failure alert for flow {{ flow.namespace }}.{{ flow.id }}"
    htmlTextContent: "Test output"
    executionId: "{{ execution.id }}"
```

**Comment by anna-geller** [comment]
Can you show a screenshot? I think MailExecution doesn't allow any custom message, the properties don't seem to have any effect

**Comment by Ben8t** [comment]
I'm able to reproduce:

```yaml
id: mail_execution
namespace: dev.ben

tasks:
  - id: bad_log_task
    type: io.kestra.plugin.core.log.Log
    message: "{{inputs.test}}"

errors:
  - id: mail
    type: io.kestra.plugin.notifications.mail.MailExecution
    from: onboardin@resend.dev
    to: bpimpaud@kestra.io
    username: resend
    host: smtp.resend.com
    port: 465
    password: "re_2kJnBrC3_LwWD2aNhqzUFcJ8KPu5Gvxp1"
    sessionTimeout: 6000
    subject: "Failure alert for flow {{ flow.namespace }}.{{ flow.id }}"
    htmlTextContent: "Test output"
    executionId: "{{ execution.id }}"
```

-> you can create a Resend account, create an API key and you will be able to send email to your related email account

![image](https://github.com/user-attachments/assets/e687063b-9aa5-44e4-bf69-098d6e8d50b0)

**Comment by mgabelle** [comment]
So in the code the current behavior is that we have the `htmlTextContent` that is overwritten by the Pebble email template `mail-template.hbs.peb` which currently give this shape at the email. That's the reason why we end up with nothing when the `htmlTextContent` is filled up.

Now we have two choices : 

1. We consider `htmlTextContent` is a custom HTML template and when filled we just ignore the default template   `mail-template.hbs.peb`
2. We consider `htmlTextContent` as an extra HTML and we inject it into the current template at some places.

Looking at the existing code I would choose the first option as it would allow the user to create its own MailExecution template.

**Comment by Ben8t** [comment]
Yes, let's go for the first option please

**Comment by anna-geller** [comment]
No no, let's go for the second option and add that `htmlTextContent` as an extra HTML and inject it into the current template at the beginning, i.e. first show the user's specific text they want to show and below all the standard info. 

To explain why: the purpose of `MailExecution` task is to send an alert about the **execution status**, but when user provides some custom message through `htmlTextContent` or `customMessage`, then that should be shown on top of the standard info. If we would go for the first option, it would have 1:1 the same functionality as the `MailSend` task.

**Comment by mgabelle** [comment]
We can do that but if we do we will have duplicate. What I mean is that when looking at the code we can already use `customMessage` as HTML. It's just a variable injected into the HTML template so it can be either text or HTML.

**Comment by mgabelle** [comment]
You said here : https://github.com/kestra-io/plugin-notifications/issues/196#issuecomment-2650750287

>  alternative property is `customMessage` and it works but doesn't render things well 
Unfortunately I don't know if it is possible to format correctly as we just put an entire block of text inside HTML. 
Maybe if some formatted HTML is provided it will be rendered correctly but it'd be the user's responsibility.

**Comment by anna-geller** [comment]
hmm interesting, in that case, how about deprecating customMessage and keep only the `htmlTextContent`? seems they do the same in the end?

**Comment by mgabelle** [comment]
It makes sense to me 👍🏻 ;) Let's go for this

**Comment by mgabelle** [comment]
Looking back at it we cannot deprecate the `customMessage` property. It's a property shared between several notifications tasks so it would be doable but it wouldn't make sense IMO.  

At this point I don't think we should do any more changes or maybe ask for someone else's opinion.

**Comment by anna-geller** [comment]
Matt, reminder that 
1. `htmlTextContent` this property doesn't work! it has no functionality. I showed in the issue that it's not used at all
2. `customMessage` doesn't render

**Comment by anna-geller** [comment]
discussed with Ludo, we will use `customMessage` in a markdown format as a way to provide extra message that is shown at the top before showing other content from the default template.

`htmlTextContent` should be removed entirely as it's not working anyway but remove it without crashing -- i.e. put a Setter to make the flow not crash but not use Getter so that it's not within the plugin documentation - empty placeholder preventing the flow from crashing

**Comment by Ben8t** [comment]
@mgabelle I've been playing with the task recently on [preview env.](https://postgres-ee.preview.dev.kestra.io/ui/executions/dev.ben/email_test/REri54kTcyOywAG4jm60b/gantt), and while the customMessage property works correctly, the htmlTextContent and plainTextContent properties still shows up and are valid from the flow definition:

```yaml
id: email_test
namespace: dev.ben

tasks:

  - id: get_files
    type: io.kestra.plugin.core.http.Download
    uri: https://dummyjson.com/products

  
  - id: get_image
    type: io.kestra.plugin.core.http.Download
    uri: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZiiKzlN_hGZANoZdyV1wIlZkXZ6vjDCxsbQ&s

  - id: send_email
    type: io.kestra.plugin.notifications.mail.MailExecution
    from: onboardin@resend.dev
    to: bpimpaud@kestra.io
    attachments:
      - name: test.json
        uri: "{{ outputs.get_files.uri }}"
        contentType: "application/json"
    embeddedImages:
      - name: test.jpg
        uri: "{{ outputs.get_image.uri }}"
    username: resend
    password: "XXXX"
    host: smtp.resend.com
    port: 465
    customMessage: test
    htmlTextContent:
      <body><h1>This is htmlTextContent property</h1></body>
    plainTextContent: This is plainTextContent property
    subject: Test from Kestra
triggers:
  - id: run_after_extract
    type: io.kestra.plugin.core.trigger.Flow
    preconditions:
      id: flows
      flows:
        - namespace: dev.ben
          flowId: test_trigger
          states: [SUCCESS]
```

![Image](https://github.com/user-attachments/assets/32eea157-f23e-41ed-ae4b-1e6fc71265ef)

LMK if I'm wrong, but the updated made here should be available on preview right (PR merged 3 weeks ago)?
