### ISSUE TITLE
SlackExecution task fails with`body:[0x36]invalid_blocks`

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/plugin-notifications#207]
### Describe the issue

```yaml
id: alert_sanitychecks
namespace: sanitychecks

tasks:
  - id: send_alert
    type: io.kestra.plugin.notifications.slack.SlackExecution
    url: "{{ secret('SANITYCHECK_SLACK_WEBHOOK') }}"
    executionId: "{{ trigger.executionId }}"

triggers:
  - id: on_failure
    type: io.kestra.plugin.core.trigger.Flow
    conditions:
      - type: io.kestra.plugin.core.condition.ExecutionStatus
        in:
          - FAILED
          - WARNING
      - type: io.kestra.plugin.core.condition.ExecutionNamespace
        namespace: sanitychecks
        prefix: true
```
We got the following error: `Failed http request with response code '400' and body:[0x36]invalid_blocks`

![image](https://github.com/user-attachments/assets/52757545-d39e-4c0e-9b6c-bc5ac1feea57)

### Environment

- Kestra Version: develop
