### ISSUE TITLE
TeamsExecution -

### ISSUE THREAD

**Issue by theompm** [kestra-io/plugin-notifications#208]
### Describe the issue

# Teams Workflow Error:

```
The execution of template action 'Send_each_adaptive_card' failed:
the result of the evaluation of 'foreach' expression '@triggerOutputs()?['body']?['attachments']' is of type 'Null'. The result must be a valid array.
````

# My Flow: SUCCEEDS

```yaml
id: failure_alert
namespace: company

tasks:
  - id: send_alert
    type: io.kestra.plugin.notifications.teams.TeamsExecution
    url: "{{ kv('teams-webhook') }}"
    executionId: "{{ trigger.executionId }}"
    activityTitle: "Kestra Failure Alert"


triggers:
  - id: failed_workflows
    type: io.kestra.plugin.core.trigger.Flow
    conditions:
      - type: io.kestra.plugin.core.condition.ExecutionStatus
        in:
          - SUCCESS # for testing 
          - FAILED
          - WARNING
      - type: io.kestra.plugin.core.condition.ExecutionNamespace
        namespace: company
        prefix: true
```

## Output

```json
Send Microsoft Teams webhook: 

{
    "@type": "MessageCard",
    "@context": "http://schema.org/extensions",
    "themeColor": "0076D7",
    "summary": "*<[http://localhost:8080/ui/executions/company.terminology/dbt_terminology/E5IAqVhBd2ggCD8t8dCuh|[company.terminology]](http://localhost:8080/ui/executions/company.terminology/dbt_terminology/E5IAqVhBd2ggCD8t8dCuh%7C[company.terminology]) dbt_terminology ➛ SUCCESS>*\n> Succeeded after 00:00:15.143",
    "sections": [{
        "activityTitle": "Kestra Failure Alert",
        "facts": [{
            "name": "Namespace",
            "value": "company.terminology"
        }, {
            "name": "Flow ID",
            "value": "dbt_terminology"
        }, {
            "name": "Execution ID",
            "value": "E5IAqVhBd2ggCD8t8dCuh"
        }, {
            "name": "Execution Status",
            "value": "SUCCESS"
        }, {
            "name": "Final task ID",
            "value": "drop_storage"
        }],
        "markdown": true
    }]
}
```
```
Request '[URL]' from '[URL]' with the response code '202'
```
```
Response: 
```

### SCHEMA.org

http://schema.org/extensions

Error: Not Found
The requested URL /extensions was not found on this server.

### Environment

- Kestra Version: 22.2
