### ISSUE TITLE
Discord notify error

### ISSUE THREAD

**Issue by Vinceveve** [kestra-io/plugin-notifications#210]
### Describe the issue

Discord  notification gives and error : 

` Execution failed! With last error: Failed http request with response code '400' and body:[0x36]{"_misc": ["Only dictionaries may be used in a DictType"]}`

It's working in previous version, but can't make it work with all 0.22

```yaml
- id: notify
  type: io.kestra.plugin.notifications.discord.DiscordExecution
  url: https://discord.com/api/webhooks/xxxx
  username: "Working"
  embedList:
      - title: "title"
      - description: "whatever"
```

### Environment

- Kestra Version: 0.22.x
