### ISSUE TITLE
Allow adding proxy to MailSend plugin

### ISSUE THREAD

**Issue by alphakilo7** [kestra-io/plugin-notifications#214]
### Feature description

I am working inside corporate proxy network. In my flow, I'm trying to send email whenever and error occurs. Below is my flow:
```
Hello all,
I am trying to trigger emails through my Kestra flow. There is a unified mail gateway setup in my org. I believe we need to setup proxy, but there is no option to set proxy for MailSend plugin. Below is my flow:
 id: unreliable_flow
 namespace: company.team
 
 tasks:
   - id: fail
     type: io.kestra.plugin.scripts.shell.Commands
     taskRunner:
       type: io.kestra.plugin.core.runner.Process
     commands:
       - exit 1
     warningOnStdErr: false
 
 errors:
   - id: send_email
     type: io.kestra.plugin.notifications.mail.MailSend
     from: SpotlightServices@myorg.net
     to: "name1@myorg.net;name2@myorg.net"
     transportStrategy: SMTP
     host: "umg.myorg.net"
     port: 25
     subject: "Kestra workflow failed: {{ flow.namespace }}.{{ flow.id }}"
     htmlTextContent: |
       <p><strong>Failure Alert</strong></p>
       <p>Flow: <code>company.team.unreliable_flow</code></p>
       <p>Execution ID: <code>abc123-execution-id</code></p>
       <p>Status: <code>FAILED</code></p>
       <p>Time: <code>2025-04-17T12:34:56Z</code></p>
       <p>Please check the logs for more details.</p>
```
For this workflow run, I'm getting below error:
```
 2025-04-17 19:41:24.076org.simplejavamail.mailer.internal.MailerException: Failed to send email [Subject: 'Kestra workflow failed: company.team.unreliable_flow'], reason: Third party error
     at org.simplejavamail.mailer.internal.SendMailClosure.handleException(SendMailClosure.java:85)
     at org.simplejavamail.mailer.internal.SendMailClosure.executeClosure(SendMailClosure.java:72)
     at org.simplejavamail.mailer.internal.AbstractProxyServerSyncingClosure.run(AbstractProxyServerSyncingClosure.java:59)
     at org.simplejavamail.mailer.internal.MailerImpl.sendMail(MailerImpl.java:364)
     at org.simplejavamail.mailer.internal.MailerImpl.sendMail(MailerImpl.java:349)
     at io.kestra.plugin.notifications.mail.MailSend.run(MailSend.java:207)
     at io.kestra.plugin.notifications.mail.MailSend.run(MailSend.java:33)
     at io.kestra.core.runners.WorkerTaskCallable.doCall(WorkerTaskCallable.java:78)
     at io.kestra.core.runners.AbstractWorkerCallable.call(AbstractWorkerCallable.java:62)
     at io.kestra.core.runners.WorkerSecurityService.callInSecurityContext(WorkerSecurityService.java:10)
     at io.kestra.core.runners.Worker.lambda$callJob$19(Worker.java:837)
     at io.kestra.core.trace.NoopTracer.inCurrentContext(NoopTracer.java:15)
     at io.kestra.core.runners.Worker.callJob(Worker.java:833)
     at io.kestra.core.runners.Worker.runAttempt(Worker.java:792)
     at io.kestra.core.runners.Worker.run(Worker.java:640)
     at io.kestra.core.runners.Worker.handleTask(Worker.java:332)
     at io.kestra.core.runners.Worker.lambda$run$8(Worker.java:261)
     at io.micrometer.core.instrument.internal.TimedRunnable.run(TimedRunnable.java:49)
     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
     at java.base/java.lang.Thread.run(Unknown Source)
 Caused by: jakarta.mail.MessagingException: Could not convert socket to TLS;
   nested exception is:
     javax.net.ssl.SSLHandshakeException: No name matching umg.myorg.net found
     at org.eclipse.angus.mail.smtp.SMTPTransport.startTLS(SMTPTransport.java:2173)
     at org.eclipse.angus.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:741)
     at jakarta.mail.Service.connect(Service.java:345)
     at jakarta.mail.Service.connect(Service.java:225)
     at jakarta.mail.Service.connect(Service.java:174)
     at org.simplejavamail.mailer.internal.util.TransportConnectionHelper.connectTransport(TransportConnectionHelper.java:42)
     at org.simplejavamail.mailer.internal.util.TransportRunner.runOnSessionTransport(TransportRunner.java:80)
     at org.simplejavamail.mailer.internal.util.TransportRunner.sendMessage(TransportRunner.java:56)
     at org.simplejavamail.mailer.internal.SendMailClosure.executeClosure(SendMailClosure.java:69)
     ... 19 more
 Caused by: javax.net.ssl.SSLHandshakeException: No name matching umg.myorg.net found
     at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
     at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
     at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
     at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
     at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(Unknown Source)
     at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(Unknown Source)
     at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(Unknown Source)
     at java.base/sun.security.ssl.SSLHandshake.consume(Unknown Source)
     at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
     at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
     at java.base/sun.security.ssl.TransportContext.dispatch(Unknown Source)
     at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
     at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
     at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
     at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
     at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
     at org.eclipse.angus.mail.util.SocketFetcher.configureSSLSocket(SocketFetcher.java:662)
     at org.eclipse.angus.mail.util.SocketFetcher.startTLS(SocketFetcher.java:563)
     at org.eclipse.angus.mail.smtp.SMTPTransport.startTLS(SMTPTransport.java:2168)
     ... 27 more
 Caused by: java.security.cert.CertificateException: No name matching umg.myorg.net found
     at java.base/sun.security.util.HostnameChecker.matchDNS(Unknown Source)
     at java.base/sun.security.util.HostnameChecker.match(Unknown Source)
     at java.base/sun.security.ssl.X509TrustManagerImpl.checkIdentity(Unknown Source)
     at java.base/sun.security.ssl.X509TrustManagerImpl.checkIdentity(Unknown Source)
     at java.base/sun.security.ssl.AbstractTrustManagerWrapper.checkAdditionalTrust(Unknown Source)
     at java.base/sun.security.ssl.AbstractTrustManagerWrapper.checkServerTrusted(Unknown Source)
     ... 42 more
```
Note: my internal network uses unified mail gateway.
