### ISSUE TITLE
Add headers to Request options on HTTP-based notification plugins like SlackIncomingWebhook

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-notifications#218]
### Feature description

Reqres now requires an API key: https://reqres.in/signup

![Image](https://github.com/user-attachments/assets/0264a044-513c-4042-965c-e2a43263d938)

I'm surprised that HTTP options don't allow setting request headers, we should fix that:

```yaml
id: approval
namespace: company

inputs:
  - id: request
    type: STRING
    defaults: John Doe requests PTO for last 2 weeks of July 2025

tasks:
  - id: sendApprovalRequest
    type: io.kestra.plugin.notifications.slack.SlackIncomingWebhook
    options:
      headers:
        x-api-key: reqres-free-v1
    url: https://reqres.in/api/slack
    payload: |
      {
        "channel": "#vacation",
        "text": "Validate PTO. To approve the request, click on the `Resume` button here {{kestra.url}}/ui/executions/{{flow.namespace}}/{{flow.id}}/{{execution.id}}"
      }
```
