### ISSUE TITLE
Discord plugin is not working anymore

### ISSUE THREAD

**Issue by HeribertoAlves** [kestra-io/plugin-notifications#226]
### Describe the issue

When flow is called I got the error: Failed http request with response code '400' and body:[0x36]
{"_misc": ["Only dictionaries may be used in a DictType"]}

trigger.body.detailedMessage.text  contains the commit message from git

    "text": "Azure FEESC pushed 2 commits to timoneiro-municipal:master\r\n - Merge branch 'hotfix/BUG_3382' 45626eaf (https://dev.azure.com/feesc-ti/Timoneiro/_git/timoneiro-municipal/commit/72342dsffsdjkh32)\r\n - BUG_3382 kestra-io/kestra#3382 Foi feita alteração utilizando a tabela nova do sql server e tamb 853655f2 (https://dev.azure.com/feesc-ti/Timoneiro/_git/timoneiro-municipal/commit/853655f2eb4c0463e914c94d65a9f1922dba1e92)"

My flow below:

id: discord_alert
namespace: online.timoneiro.discord
description: Send message to Discord  channel 

tasks:
  - id: send_discord_message
    type: io.kestra.plugin.notifications.discord.DiscordExecution
    url : "{{ secret('DISCORD') }}"
    username: "Kestra"
    avatarUrl: "https://avatars.githubusercontent.com/u/59033362?v=4"
    embedList:
      - title: Azure Devops Notification
        color:
          - 255
          - 255
          - 255
        websiteUrl: "https://dev.azure.com/feesc-ti/Timoneiro/"
    content: "Info: {{ trigger.body.detailedMessage.text | abbreviate(1945)}}" 

    

triggers:
  - id: azure-devops
    type: io.kestra.plugin.core.trigger.Webhook
    key: "MYKEY"
disabled: false

### Environment

- Kestra Version: 0.22.6

**Comment by Ben8t** [comment]
Hello, can you try on develop image please? We got this issue resolved lately that sounds very similar (if not the same) https://github.com/kestra-io/plugin-notifications/issues/210

**Comment by HeribertoAlves** [comment]
Hello @Ben8t ! I'll try today and give you feedback.

**Comment by HeribertoAlves** [comment]
@Ben8t Now I got the error below. 
url: https://discord.com/api/webhooks/1...../A......... 
Title: Test
Message: Teste message

Version: 0.23.0-SNAPSHOT

java.util.NoSuchElementException
	at java.base/java.util.List.getLast(Unknown Source)
	at io.kestra.plugin.notifications.services.ExecutionService.executionMap(ExecutionService.java:107)
	at io.kestra.plugin.notifications.discord.DiscordExecution.run(DiscordExecution.java:72)
	at io.kestra.plugin.notifications.discord.DiscordExecution.run(DiscordExecution.java:16)
	at io.kestra.core.runners.WorkerTaskCallable.doCall(WorkerTaskCallable.java:79)
	at io.kestra.core.runners.AbstractWorkerCallable.call(AbstractWorkerCallable.java:63)
	at io.kestra.core.runners.WorkerSecurityService.callInSecurityContext(WorkerSecurityService.java:10)
	at io.kestra.core.runners.Worker.lambda$callJob$19(Worker.java:853)
	at io.kestra.core.trace.NoopTracer.inCurrentContext(NoopTracer.java:15)
	at io.kestra.core.runners.Worker.callJob(Worker.java:849)
	at io.kestra.core.runners.Worker.runAttempt(Worker.java:807)
	at io.kestra.core.runners.Worker.run(Worker.java:654)
	at io.kestra.core.runners.Worker.handleTask(Worker.java:353)
	at io.kestra.core.runners.Worker.lambda$run$8(Worker.java:276)
	at io.micrometer.core.instrument.internal.TimedRunnable.run(TimedRunnable.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by Ben8t** [comment]
@HeribertoAlves we're not able to reproduce the error

```yaml
id: lark_268734
namespace: company.team

tasks:
  - id: alert
    type: io.kestra.plugin.notifications.discord.DiscordExecution
    url: https://discord.com/api/webhooks/1364592814943633438/EE4EAg-vLFw-Dsbcu3Rowzcmzlfy148zYOPgB1a7xAmo6Eyy5MRf2WCVlp8aX1fBb7Fn
    username: "Kestra"
    avatarUrl: "https://avatars.githubusercontent.com/u/59033362?v=4"
    embedList:
      - title: Azure Devops Notification
        color:
          - 255
          - 255
          - 255
        websiteUrl: "https://google.com"
    content: "Info: {{ execution.id }}"
    
triggers:
  - id: run_after_extract
    type: io.kestra.plugin.core.trigger.Flow
    preconditions:
      id: flows
      flows:
        - namespace: company.team
          states: [FAILED]
```

The message is send correclty without the error you reported:
![Image](https://github.com/user-attachments/assets/b69898ed-a0f2-41f7-b0d3-372c935ee34b)


Can you give us more details on how we can reproduce? Can you try we something simpler in `{{ trigger.body.detailedMessage.text | abbreviate(1945)}}`, maybe the message here cause the issue
