### ISSUE TITLE
Make SlackIncomingWebhook more resilient

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-notifications#227]
### Describe the issue

Currently, this task can only work with a simple payload with no special characters. Already adding a markdown URL reference with some extra spaces in the text will make the task break and makes me want to switch from this plugin to a self-made Python script 😭 

`Illegal unquoted character ((CTRL-CHAR, code 10)): has to be escaped using backslash to be included in string value
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 36]`

Reproducer:

```yaml
id: fetch_local_news
namespace: company.team

inputs:
  - id: prompt
    type: STRING
    defaults: Summarize top 5 news from my region. 

tasks:
  - id: news
    type: io.kestra.plugin.openai.Responses
    apiKey: "{{ kv('OPENAI_API_KEY') }}"
    model: gpt-4.1-mini
    input: "{{ inputs.prompt }}"
    toolChoice: REQUIRED
    tools:
      - type: web_search_preview
        search_context_size: low  # optional; low, medium, high
        user_location:
          type: approximate # OpenAI doesn't provide other types atm, and it cannot be omitted
          city: Berlin
          region: Berlin
          country: DE
          
  - id: send_via_slack
    type: io.kestra.plugin.notifications.slack.SlackIncomingWebhook
    url: https://kestra.io/api/mock
    payload: |
      {
        "text": "Current news from Berlin: {{ outputs.news.outputText }}"
      }
```

Even trying to do some magic in replacing newlines etc fails:

```yaml
  - id: send_via_slack
    type: io.kestra.plugin.notifications.slack.SlackIncomingWebhook
    url: https://kestra.io/api/mock
    payload: |
      {
        "text": "Current news from Berlin:  {{ outputs.news.outputText | replace({'\n': '\\n'}) }}"
      }
```

## Expected outcome

User should be able to pass ANY arbitrary string as payload and our backend should do the work to figure out how to handle encoding/processing of special characters.

### Environment

- Kestra Version: develop

**Comment by anna-geller** [comment]
Example output text:

```markdown
Here are the top five recent news stories from Berlin: 1. **Cirque du Soleil Announces First Permanent European Show in Berlin** Cirque du Soleil has chosen Berlin's Potsdamer Platz as the venue for its first permanent European show, titled "Alize," set to debut in November 2025. The production will transform the Theater at Potsdamer Platz to accommodate its unique technical needs, offering acrobatic acts, mesmerizing magic, and captivating artistry. Tickets are now available for purchase. ([reuters.com](https://www.reuters.com/lifestyle/cirque-du-soleil-picks-berlin-first-permanent-european-show-2024-11-20/?utm_source=openai)) 2. **Berlin's Arts Scene Faces Severe Budget Cuts** The Berlin government plans to reduce next year's arts budget by €130 million as part of a broader austerity measure to address public finances. This decision has sparked significant backlash from the arts community, leading to protests and public pleas against the cuts. Major institutions like opera houses and theaters, as well as the independent and underground arts scenes, are expected to suffer. The government argues that spending has been excessive and unsustainable, suggesting that the arts sector should seek private sponsorship and become more economically efficient. Critics argue that these cuts threaten the very soul of Berlin, endangering its cultural vibrancy and appeal to tourists. ([ft.com](https://www.ft.com/content/37e19262-ccba-4d87-b825-929c998f5872?utm_source=openai)) 3. **NFL Announces First-Ever Regular Season Game in Berlin for 2025** The NFL will hold its first-ever regular season game in Berlin in 2025 at Olympic Stadium as part of its global expansion efforts. This match will be the fifth regular season game in Germany, following previous games in Munich and Frankfurt since 2022. In collaboration with the Berlin Senate, the NFL aims to promote and develop flag football in Berlin's schools and clubs, in line with its inclusion in the 2028 Los Angeles Olympics. NFL Commissioner Roger Goodell highlighted Berlin's historical connection with American football, including past preseason games and NFL Europe's Berlin Thunder. The full list of international game hosts and participating teams for 2025 will be announced later. ([reuters.com](https://www.reuters.com/sports/nfl/nfl-announces-first-ever-regular-season-game-berlin-2025-2024-12-11/?utm_source=openai)) 4. **Berlin's New Panda Twins Have Been Named** Berlin Zoo's new panda twins, born on August 22, have been named Meng Hao and Meng Tian, meaning "beautiful dreams" and "sweet dreams." Alternatively, they are also known as Leni and Lotti, in honor of Berlin native Marlene Dietrich and Charlottenburg district. The twin female cubs are the second pair of giant pandas born in Germany, following their elder brothers Meng Xiang and Meng Yuan (Pit and Paule), who were born in 2019. The twins’ parents, Meng Meng and Jiao Qing, arrived in Berlin in 2017. The young pandas are growing rapidly, gaining almost 100 grams daily and currently weighing nearly 6 kilos each. Initially, one cub will be available for visitors to see daily, and both will be viewable with their mother from late January. ([apnews.com](https://apnews.com/article/baa96a2f489aa4be72b9c1335c4a774c?utm_source=openai)) 5. **Former Stasi Officer Sentenced for 1974 Border Killing** An 80-year-old former Stasi officer was sentenced to 10 years in prison for the murder of Polish citizen Czesław Kukuczka at a Berlin border crossing in 1974. The Berlin court confirmed that the then-first lieutenant executed the killing under Stasi orders. The judge labeled the act as planned and merciless. The prosecution had sought a 12-year sentence, but the defense demanded an acquittal, arguing the client did not fire the fatal shot. The case, reopened after a tip-off in 2016 from Stasi records, detailed Kukuczka’s attempt to flee to West Berlin. He was shot in the back after being deceptively provided with exit documents and led to a border crossing. The verdict is subject to appeal. ([apnews.com](https://apnews.com/article/8cde4b1a8a6537e841977fc4fc442bcf?utm_source=openai)) ## Top Berlin News Stories: - [Cirque du Soleil picks Berlin for first permanent European show](https://www.reuters.com/lifestyle/cirque-du-soleil-picks-berlin-first-permanent-european-show-2024-11-20/?utm_source=openai) - [Berlin cries Kulturkrise as cuts hit arts scene](https://www.ft.com/content/37e19262-ccba-4d87-b825-929c998f5872?utm_source=openai) - [NFL announces first-ever regular season game in Berlin for 2025](https://www.reuters.com/sports/nfl/nfl-announces-first-ever-regular-season-game-berlin-2025-2024-12-11/?utm_source=openai)
```

![Image](https://github.com/user-attachments/assets/8bb4053f-28c2-495a-a439-337e06406871)

**Comment by anna-geller** [comment]
Will test and validate, thanks Brian 🙏

**Comment by anna-geller** [comment]
the double rendering PR didn't seem to change anything, or perhaps was the fix not included in develop yet?

![Image](https://github.com/user-attachments/assets/2f881ea7-a8e8-4779-ade5-828cc84a6e66)

flow I used:

```yaml
id: fetch_local_news
namespace: company.team

inputs:
  - id: prompt
    type: STRING
    defaults: Summarize top 5 news from my region. 

tasks:
  - id: news
    type: io.kestra.plugin.openai.Responses
    apiKey: "{{ kv('OPENAI_API_KEY') }}"
    model: gpt-4.1-mini
    input: "{{ inputs.prompt }}"
    toolChoice: REQUIRED
    tools:
      - type: web_search_preview
        search_context_size: low  # optional; low, medium, high
        user_location:
          type: approximate # OpenAI doesn't provide other types atm, and it cannot be omitted
          city: Berlin
          region: Berlin
          country: DE

  - id: send_via_slack_1
    type: io.kestra.plugin.notifications.slack.SlackIncomingWebhook
    url: https://kestra.io/api/mock
    payload: |
      {{
        {
          "text": "Current news from Berlin: " ~ outputs.news.outputText
        }
      }}

  - id: send_via_slack_2
    type: io.kestra.plugin.notifications.slack.SlackIncomingWebhook
    url: https://kestra.io/api/mock
    payload: |
      {
        "text": "Current news from Berlin: {{ outputs.news.outputText }}"
      }
```

**Comment by anna-geller** [comment]
now also tried this option from Brian `{{ outputs.news.outputText | replace({'"': '\"'}) }}`  -- this one still didn't work, see image below

```yaml
id: fetch_local_news
namespace: company.team

inputs:
  - id: prompt
    type: STRING
    defaults: Summarize top 5 news from my region. 

tasks:
  - id: news
    type: io.kestra.plugin.openai.Responses
    apiKey: "{{ kv('OPENAI_API_KEY') }}"
    model: gpt-4o
    input: "{{ inputs.prompt }}"
    toolChoice: REQUIRED
    tools:
      - type: web_search_preview
        search_context_size: low  # optional; low, medium, high
        user_location:
          type: approximate # OpenAI doesn't provide other types atm, and it cannot be omitted
          city: Berlin
          region: Berlin
          country: DE
          
  - id: send_via_slack
    type: io.kestra.plugin.notifications.slack.SlackIncomingWebhook
    url: https://kestra.io/api/mock
    payload: |
      {
        "text": "Current news from Berlin: {{ outputs.news.outputText | replace({'"': '\"'}) }}"
      }
```

![Image](https://github.com/user-attachments/assets/31516a18-727b-46bc-b4e2-58d7ba72e440)

(thanks for troubleshooting with me @brian-mulier-p!)

---

so far, the magic syntax is the only option that works:

```yaml
- id: send_via_slack
    type: io.kestra.plugin.notifications.slack.SlackIncomingWebhook
    url: https://kestra.io/api/mock
    payload: |
      {{
        {
          "text": "Current news from Berlin: " ~ outputs.news.outputText
        }
      }}
```

## Next steps

Let's revisit this in the 0.24 cycle, perhaps we can **introduce a new plugin property** that would allow passing an **opinionated version of payload** e.g. string property `payloadText`, `messageText` or `message` (naming TBD) -- this would allow us to pass the Slack message text more declaratively in YAML without the complexity of the raw JSON body. Less flexible option as it won't allow arbitrary blocks, but it will be more reliable/resilient as we construct the payload for the user under the hood, and the user doesn't need to worry about any special characters.

**Comment by Malaydewangan09** [comment]
@anna-geller , I got something working for this now, added a new Property `messageText` (name TBD)
Now just pass LLM's response as it is
Got the similar results like this

> so far, the magic syntax is the only option that works:
> 
> - id: send_via_slack
>     type: io.kestra.plugin.notifications.slack.SlackIncomingWebhook
>     url: https://kestra.io/api/mock
>     payload: |
>       {{
>         {
>           "text": "Current news from Berlin: " ~ outputs.news.outputText
>         }
>       }}
> 

```yaml
id: fetch_local_news
namespace: company.team

inputs:
  - id: prompt
    type: STRING
    defaults: Summarize top 5 news from my region. 

tasks:
  - id: news
    type: io.kestra.plugin.openai.Responses
    apiKey: "{{ kv('OPENAI_API_KEY') }}"
    model: gpt-4.1-mini
    input: "{{ inputs.prompt }}"
    toolChoice: REQUIRED
    tools:
      - type: web_search_preview
        search_context_size: low  # optional; low, medium, high
        user_location:
          type: approximate # OpenAI doesn't provide other types atm, and it cannot be omitted
          city: Berlin
          region: Berlin
          country: DE

  - id: send_via_slack_3
    type: io.kestra.plugin.notifications.slack.SlackIncomingWebhook
    url: https://kestra.io/api/mock
    messageText: "Current news from Berlin: {{ outputs.news.outputText }}"
 ```

Just some issues, e.g LLM's bold text is recieved as **something**, while slack doesn't render it as bold instead it renders as it is, see image below

<img width="1057" height="506" alt="Image" src="https://github.com/user-attachments/assets/1bff5997-3613-4b29-a033-d34ec4318ef6" />

**Comment by Malaydewangan09** [comment]
@anna-geller @fdelbrayelle  , I got something working for this now, added a new Property `messageText` (name TBD)
Now just pass LLM's response as it is
Got the similar results like this

> so far, the magic syntax is the only option that works:
> 
> - id: send_via_slack
>     type: io.kestra.plugin.notifications.slack.SlackIncomingWebhook
>     url: https://kestra.io/api/mock
>     payload: |
>       {{
>         {
>           "text": "Current news from Berlin: " ~ outputs.news.outputText
>         }
>       }}
> 

```yaml
id: fetch_local_news
namespace: company.team

inputs:
  - id: prompt
    type: STRING
    defaults: Summarize top 5 news from my region. 

tasks:
  - id: news
    type: io.kestra.plugin.openai.Responses
    apiKey: "{{ kv('OPENAI_API_KEY') }}"
    model: gpt-4.1-mini
    input: "{{ inputs.prompt }}"
    toolChoice: REQUIRED
    tools:
      - type: web_search_preview
        search_context_size: low  # optional; low, medium, high
        user_location:
          type: approximate # OpenAI doesn't provide other types atm, and it cannot be omitted
          city: Berlin
          region: Berlin
          country: DE

  - id: send_via_slack_3
    type: io.kestra.plugin.notifications.slack.SlackIncomingWebhook
    url: https://kestra.io/api/mock
    messageText: "Current news from Berlin: {{ outputs.news.outputText }}"
 ```

<img width="1057" height="494" alt="Image" src="https://github.com/user-attachments/assets/3a47732f-8af1-4dd2-b57f-790e18460ecb" />
