### ISSUE TITLE
Telegram: Unrecognized field "message_id"

### ISSUE THREAD

**Issue by r4mp** [kestra-io/plugin-notifications#231]
### Describe the issue

If I try to send a telegram message via `io.kestra.plugin.notifications.telegram.TelegramExecution` or `io.kestra.plugin.notifications.telegram.TelegramSend` the flow fails with the following error. But I receive the telegram message.

```java
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "message_id" (class io.kestra.plugin.notifications.telegram.TelegramBotApiService$TelegramMessage), not marked as ignorable (2 known properties: "chat_id", "text"])
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 662] (through reference chain: io.kestra.plugin.notifications.telegram.TelegramBotApiService$TelegramBotApiResponse["result"]->io.kestra.plugin.notifications.telegram.TelegramBotApiService$TelegramMessage["message_id"])
```

```
id: telegram_test
namespace: kestra
tasks:
  - id: send_alert
    type: io.kestra.plugin.notifications.telegram.TelegramSend
    token: "{{ secret('TELEGRAM_TOKEN') }}"
    channel: "-12345678"
    payload: "ABCD"
```

```
id: failure_alert_kestra_namespace
namespace: kestra
tasks:
  - id: send_alert
    type: io.kestra.plugin.notifications.telegram.TelegramExecution
    token: "{{ secret('TELEGRAM_TOKEN') }}"
    channel: "-12345678"
    executionId: "{{ trigger.executionId }}"
triggers:
  - id: failed_kestra_workflows
    type: io.kestra.plugin.core.trigger.Flow
    conditions:
      - type: io.kestra.plugin.core.condition.ExecutionStatus
        in:
          - FAILED
          - WARNING
      - type: io.kestra.plugin.core.condition.ExecutionNamespace
        namespace: kestra
        prefix: true
```

### Environment

- Kestra Version: 0.22.8
