### ISSUE TITLE
Move email attachements to property V2 and support dynamic fill

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/plugin-notifications#235]
### Describe the issue

The following flow doesn't validated:

```yaml
id: email_attachments
namespace: dev.ben

inputs:
  - id: attachments
    type: ARRAY
    itemType: JSON
tasks:
  - id: send-mail
    type: io.kestra.plugin.notifications.mail.MailSend
    attachments: 
      {% for data in inputs.attachements %}
      - name: "{{ data.name }}"
        uri: "{{ data.uri }}"
      {% endfor %}
```

![Image](https://github.com/user-attachments/assets/23df7672-7657-4615-a024-9f7a98ec1726)

For ref. @loicmathieu mentioned this by Slack:
> It's because it didn't use the new Property v2, it should be possible with it (if not, we would have more power to try to make it work).

The goal is here to move to the new Property v2 ([cf. line ref. in code](https://github.com/kestra-io/plugin-notifications/blob/146eb05895013aabd07b0a0405ea9fb138c8e75e/src/main/java/io/kestra/plugin/notifications/mail/MailSend.java#L150)) and make sure the email task can be used with many dynamic attachements

### Environment

- Kestra Version: develop
