### ISSUE TITLE
Can send csv format as attachment in email.

### ISSUE THREAD

**Issue by KevinZhaoCn** [kestra-io/plugin-notifications#37]
### Feature description

Currently, there is a buy with email sending. It can not send csv format as attachment. 
So hope to resolve the problem. The details as below.
![image](https://user-images.githubusercontent.com/44827469/212033917-001205b7-5c65-40ae-bda1-77b7a2d2c838.png)

![image](https://user-images.githubusercontent.com/44827469/212033986-23a34099-e781-4edb-b67e-725c0d63a216.png)

Thanks,
Kevin

**Comment by tchiotludo** [comment]
Humm unable to reproduce the issue with this : 
```
id: mail
namespace: com.kestra.lde
revision: 5
inputs:
  - type: FILE
    name: file
    required: false
tasks:
  - id: bash
    type: io.kestra.core.tasks.scripts.Bash
    commands:
      - echo "" >> {{ outputFiles.first }}
    outputFiles:
      - first
  - id: mail
    type: io.kestra.plugin.notifications.mail.MailSend
    attachments:
      - contentType: application/octet-stream
        uri: "{{inputs.file ?? outputs.bash.files.first}}"
    from: test@kestra.io
    host: localhost
    htmlTextContent: Test Att
    port: 1025
    subject: Test Att
    to: me@xx.com
    transportStrategy: SMTP
```
Do you used the last kestra version?
