### ISSUE TITLE
plugin to get logs

### ISSUE THREAD

**Issue by Melkaz** [kestra-io/plugin-notifications#55]
### Feature description

There are cases where fetching logs from previous tasks would be useful (e.g. an error happens and we need to forward the error message to a Teams channel).

The API could look like that:

```
id: get-logs
type: <something-logs>
from:
  - taskId: task1
     level: WARN
```

Thanks !
