### ISSUE TITLE
`DiscordExecution` task fails with Bad Request

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-notifications#85]
### Feature description

Here’s what gets sent as a payload (from the logs message):

```yaml
Send Discord webhook: {"description":[{"name":"Namespace","value":"dev"},{"name":"Flow ID","value":"discord"},{"name":"Execution ID","value":"1p0JVFz24ZVLSK8iJN6hfs"},{"name":"Execution Status","value":"SUCCESS"}],"footer":"*<http://localhost:5173/ui/executions/dev/discord/1p0JVFz24ZVLSK8iJN6hfs|[dev] discord ➛ SUCCESS>*\n> Succeded after 00:00:00.385","username":"Anna","tts":false,"embeds":{"color":16777215,"title":"Discord Notification","url":"https://discord.com/api/webhooks/xx/xxx"}}
```

1. The description is sent as a list - it should be a string.
2. The footer uses Slack syntax for URL which is not supported by Discord
3. The URL is set to 5173, while it should be 8080

Here is how the correct request should look like:

```yaml
curl -X POST "https://discord.com/api/webhooks/xxx/xxx" \
-H "Content-Type: application/json" \
-d @- <<'EOF'
{
    "username": "Anna",
    "tts": false,
    "embeds": [
        {
            "color": 16777215,
            "title": "Discord Notification",
            "description": "Namespace: dev\nFlow ID: discord\nExecution ID: 1p0JVFz24ZVLSK8iJN6hfs\nExecution Status: SUCCESS\n\n[Link to the Execution page](http://localhost:8080/ui/executions/dev/discord/1p0JVFz24ZVLSK8iJN6hfs)",
            "footer": {
                "text": "Succeded after 00:00:00.385"
            }
        }
    ]
}
EOF
```

This will nicely render the result: as follows

![image](https://github.com/kestra-io/plugin-notifications/assets/86264395/8257f386-13e1-4b47-9867-8af7fd880a9b)

### Reproducer

```yaml
id: discord
namespace: dev

tasks:
  - id: log
    type: io.kestra.core.tasks.log.Log
    message: hello
```

```yaml
id: discord_alert
namespace: dev

tasks:
  - id: send_discord_message
    type: io.kestra.plugin.notifications.discord.DiscordExecution
    url: "{{ secret('DISCORD_WEBHOOK') }}"
    username: Anna
    title: "Discord Notification"
    color:
      - 255
      - 255
      - 255
    executionId: "{{trigger.executionId}}"

triggers:
  - id: itself
    type: io.kestra.core.models.triggers.types.Flow
    conditions:
      - type: io.kestra.core.models.conditions.types.ExecutionFlowCondition
        namespace: dev
        flowId: discord
      - type: io.kestra.core.models.conditions.types.ExecutionStatusCondition
        in:
          - SUCCESS
```
