### ISSUE TITLE
ZendutyExecution uses an invalid payload

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-notifications#94]
### Feature description

```
Send Zenduty webhook: {"service":"34wkwWLfa6fCacOfxFp7Rz","summary":"Namespace dev, Flow ID hello_zen, Execution ID 34wkwWLfa6fCacOfxFp7Rz, Execution Status SUCCESS. *<http://localhost:5173/ui/executions/dev/hello_zen/34wkwWLfa6fCacOfxFp7Rz|[dev] hello_zen ➛ SUCCESS>*\n> Succeded after 00:00:01.269","title":"Kestra flow failed"}
2023-10-16 21:01:26.022{"error": "Invalid payload"}
```

![image](https://github.com/kestra-io/plugin-notifications/assets/86264395/34364a46-cdaf-404e-9e6e-025f48ff57d9)

@iNikitaGricenko please check again -- I believe we need to use API integration rather than the Incident API for both ZendutyAlert and ZendutyExecution: https://docs.zenduty.com/docs/integrations 

this is the best API reference for you: https://docs.zenduty.com/docs/api 

![image](https://github.com/kestra-io/plugin-notifications/assets/86264395/8f77c60b-97bd-4cae-b902-4c4e769d3cf7)

![image](https://github.com/kestra-io/plugin-notifications/assets/86264395/2e34f39e-7613-4598-918c-1c8f7d046fc2)

**Comment by anna-geller** [comment]
Surprisingly, even explicitly overriding the payload doesn't work

```yaml
id: failure_alert
namespace: dev.monitoring

tasks:
  - id: send_alert
    type: io.kestra.plugin.notifications.zenduty.ZendutyExecution
    url: https://www.zenduty.com/api/events/xxxxxxxxxxxxxxxxx/
    title: "Kestra flow failed"
    executionId: "{{ trigger.executionId }}"
    payload: |
      {
        "alert_type": "critical",
        "message": "Kestra workflow execution {{execution.id}} failed at {{ execution.startDate }}",
        "summary": "Namespace: {{flow.namespace}}\nFlow ID: {{flow.id}}\nExecution ID: {{execution.id}}\nExecution Status: FAILED\n\n[Link to the Execution page](http://localhost:8080/ui/executions/{{flow.namespace}}/{{flow.id}}/{{execution.id}})",
        "entity_id": "{{ execution.id }}"
      }

triggers:
  - id: failed_prod_workflows
    type: io.kestra.core.models.triggers.types.Flow
    conditions:
      - type: io.kestra.core.models.conditions.types.ExecutionStatusCondition
        in:
          - FAILED
          - WARNING
      - type: io.kestra.core.models.conditions.types.ExecutionNamespaceCondition
        namespace: dev
        prefix: true
```
